### DISCUSSION TITLE
Multiple Stream Support?

### DISCUSSION THREAD

**Discussion by iercco** [lauwarm/docker-streamlink-recorder#103] [Q&A] [answered]
Hi, I've got this working great in docker-compose and was wondering if there's a way to monitor multiple different streamers.

**Comment by lauwarm** [comment, marked as answer]
Hey @iercco,

well you could just repeat the service in your docker-compose.yml.

Something like that for example:

```
version: '3.3'
services:
  streamlink-recorder-01:
    container_name: slr-01
    volumes:
      - ./vods/:/home/download
    environment:
      - streamLink=twitch.tv/01
      - streamQuality=best
      - streamName=01
      - streamOptions=--twitch-disable-reruns --twitch-disable-ads
      - uid=<your-uid>
      - gid=<your-gid>
    image: lauwarm/streamlink-recorder:latest
  streamLink-recorder-02:
    container_name: slr-02
    volumes:
      - ./vods/:/home/download
    environment:
      - streamLink=twitch.tv/02
      - streamQuality=best
      - streamName=02
      - streamOptions=--twitch-disable-reruns --twitch-disable-ads
      - uid=<your-uid>
      - gid=<your-gid>
    image: lauwarm/streamlink-recorder:latest
```

So for every stream you would add another _streamlink-recorder-01_ section to your docker-compose.yml.
