### ISSUE TITLE
Multiple parameters result in error since Streamlink 6.7.3

### ISSUE THREAD

**Issue by ch4ox** [lauwarm/docker-streamlink-recorder#114]
Hi,
since the update to Streamlink 6.7.3 I get the following error when starting a new container with my config.

The error:

```
user@docker:/var/lib/docker/volumes/twitch1# docker logs twitch1
UID : 33
GID : 33
usage: streamlink [OPTIONS] <URL> [STREAM]
streamlink: error: unrecognized arguments: source,best
```

This is my (simplified) config:

```
services:
  twitch1:
    image: lauwarm/streamlink-recorder
    container_name: twitch1
    environment:
      - "streamOptions=--twitch-disable-reruns --twitch-disable-ads"
      - "streamQuality=source,best"
      - "streamName=shroud"
      - "streamLink=twitch.tv/shroud"
    restart: always
    volumes:
      - "/mnt/download:/home/download"
```

I tried out a lot and the problem seems to be in the file streamlink-recorder.sh, specifically in this line:
`streamlink "${args[@]}" "$streamLink" "$streamQuality" -o /home/download/"$streamName"-"$Date".mkv`

Here all parameters are enclosed in " " which results in this command:
`streamlink '--twitch-disable-reruns --twitch-disable-ads' twitch.tv/shroud source,best -o /home/download/shroud-20240509-000426.mkv`

If I replace `"${args[@]}"` with `${args[@]}` (removing the ") the parameters are not enclosed in ' ' and everything works as expected.

So I think this line should read like this:
`streamlink ${args[@]} "$streamLink" "$streamQuality" -o /home/download/"$streamName"-"$Date".mkv`

I was able to fix this temporarily for me by replacing the streamlink-recorder.sh with my own version by mapping my own file as volume.

Could you please have a look at this? Thanks!
