### ISSUE TITLE
permissions on created folder

### ISSUE THREAD

**Issue by choddles** [lauwarm/docker-streamlink-recorder#16]
sudo docker run -v /home/chod/twitch/download:/home/download -e streamLink='twitch.tv/p0lyt0xxx' -e streamQuality='best' -e streamName='twitch' -e streamOptions='--twitch-disable-hosting' lauwarm/streamlink-recorder
UID : 9001
GID : 9001
[cli][info] Found matching plugin twitch for URL twitch.tv/p0lyt0xxx
[cli][info] Available streams: audio_only, 1080p (worst, best)
[cli][info] Opening stream: 1080p (hls)
error: Failed to open output: /home/download/twitch-20210523-201925.mkv ([Errno 13] Permission denied: '/home/download/twitch-20210523-201925.mkv')
[cli][info] Closing currently open stream...

apologies if/i am in error but i am quite convinced the issue is permissions inside the docker

**Comment by lauwarm** [comment]
Hey @choddles,

the log output shows a UID and GID of 9001. This is the default ID if none is specified.
UID and GID respectively stands for User ID and Group ID.

You need to use your own UID and GID of your User who has permission to write in the designated download folder (/home/chod/twitch/download).

Assuming you are on Linux, try to `cat /etc/passwd` for example. This should give you an output of all your Users and the IDs.

You then use `-e uid='' -e gid=''` option to specify the correct IDs.

**Comment by choddles** [comment]
yes, thats what i sort of figured, but still getting an error 13

'chod@R710:~$ docker run -it -v /home/:/home/download -e streamLink='twitch.tv/harddried' -e streamQuality='best' -e streamName='twitch' -e streamOptions='--twitch-disable-hosting' -e uid='1000' -e gid='1000' lauwarm/streamlink-recorder
UID : 1000
GID : 1000
[cli][info] Found matching plugin twitch for URL twitch.tv/harddried
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p50, 1080p50 (best)
[cli][info] Opening stream: 1080p50 (hls)
error: Failed to open output: /home/download/twitch-20210630-165959.mkv ([Errno 13] Permission denied: '/home/download/twitch-20210630-165959.mkv')
[cli][info] Closing currently open stream...
`
its a home folder as chod on a test box, do the internal uid/gid need to be tweeked ?

**Comment by lauwarm** [comment]
Hey @choddles

that is really strange. 

It should just work if your user `chod` has an UID and GID of 1000 and your user is able to write in /home/ because the `entrypoint.sh` switches to the specified user. The only thing I could imagine would be that it needs to run chown against the /home/download/ folder. 

Nonetheless It puzzles me. I run it as UID:GID 1026 without the permission errors.
Maybe you could double check that `chod` truly uses thoses IDs. 

As for the time being you could use `lauwarm/streamlink-recorder:python3.9.0_buster_2.0.0`.
This branch uses streamlink Version 2.0.0 but runs as root. Shouldn't give you permission errors.

**Comment by choddles** [comment]
obviously as root version works, ill experiment a bit more and report back ( probably an oddity of my setup ) , are there any -- switches for audio only , thanks

**Comment by lauwarm** [comment]
Hey @choddles 

regarding the audio only: this depends on the streaming platform itself as I understand it.

As you can see in the logs it reports back the available streams:
` [cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p50, 1080p50 (best)`

If you use `-e streamQuality='audio_only'` you would get only audio.

**Comment by squidds** [comment]
Figured I wouldn't open up another issue for this. But has anyone figured out a fix?

I tried the unpinned streamlink-recorder image on an Arch and Ubuntu host. Both with the same output:

```streamlink-recorder  | error: Failed to open output: /home/download/squiddstv-20230224-055351.mkv ([Errno 13] Permission denied: '/home/download/squiddstv-20230224-055351.mkv')```

``jellyfin:x:1000:1000:jellyfin:/home/jellyfin:/bin/bash`` G and UID on Ubuntu (same output on my Arch rig)

I am using a docker-compose file though. I don't think that makes a difference though. The pinned ``lauwarm/streamlink-recorder:python3.9.0_buster_2.0.0`` does work just fine. I don't see a reason to not continue trying to use that version, but was curious if anyone found a fix or a workaround. 

```
version: '3.3'
services:
    streamlink-recorder:
        container_name: streamlink-recorder
        volumes:
            - ./vods/:/home/download
        environment:
            - streamLink=twitch.tv/squiddstv
            - streamQuality=best
            - streamName=squiddstv
            - streamOptions=--twitch-disable-reruns --twitch-disable-ads
            - uid=1000
            - gid=1000
        image: lauwarm/streamlink-recorder

```

**Comment by lauwarm** [comment]
Hey @squidds 

I tried your Docker Compose file. 

```
fabian@Fabians-MacBook-Air ~ % id fabian
uid=501(fabian) gid=20(staff)
```

```
version: '3.3'
services:
  streamlink-recorder:
    container_name: streamlink-recorder
    volumes:
      - ./vods/:/home/download
    environment:
      - streamLink=twitch.tv/fextralife
      - streamQuality=best
      - streamName=fextralife
      - streamOptions=--twitch-disable-reruns --twitch-disable-ads
      - uid=501
      - gid=20
    image: lauwarm/streamlink-recorder
```

```
fabian@Fabians-MacBook-Air slr-test % sudo docker-compose up   
[+] Running 1/1
 ⠿ Container streamlink-recorder  Recre...                                 0.1s
Attaching to streamlink-recorder
streamlink-recorder  | UID : 501 
streamlink-recorder  | GID : 20
streamlink-recorder  | [cli][info] Found matching plugin twitch for URL twitch.tv/fextralife
streamlink-recorder  | [cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p60, 1080p60 (best)
streamlink-recorder  | [cli][info] Opening stream: 1080p60 (hls)
streamlink-recorder  | [cli][info] Writing output to
streamlink-recorder  | /home/download/fextralife-20230225-150716.mkv
streamlink-recorder  | [plugins.twitch][info] Will skip ad segments
```

As expected I get a file in the _vods_ folder. 

So far I wasn't able to reproduce the permission error. Not on a Mac, not on Windows, not on a Synology NAS.

Maybe it has something to do with UID/GID 1000?
